mylist=["aa","bbb","ccc",77,99];
print(mylist)
print(mylist[0])
print(mylist[2:4])
print(mylist[1:])
print(type(mylist))
mylist[2]="ddd"
print(mylist)
print(mylist[-1])
print(mylist[:4])
mylist.append("aaa")
print(mylist)
mylist.insert(3,"eeee")
print(mylist)
mylist.remove("eeee")
print(mylist)
mylist.extend("444")
print(mylist)
#newlist= mylist.copy()
#print(newlist)
mylist1=[["aa",1 ],["bb",2]]
print("example of multidimentional list:")
print(mylist1)
print(mylist[1][1])
print(mylist[0][0])
print(mylist[2][0])
list2=[50,25.24]
print(list2+mylist)
list2.clear()
print(list2)
name="aaaa"
myname=list(name)
print(myname)
mylist.sort()
